name: Build and Publish .NET

on:

  push:
    branches:
      - main
      - master
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
      - master
    tags:
      - 'v*'
  # Trigger on tag push to create a release
  workflow_dispatch:
  release:
    types: [created]
    tags:
      - 'v*'
permissions:
  contents: write 
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x' # Ensure this is compatible with your project

    - name: Install dependencies
      run: dotnet restore CompressMyCall.sln

    - name: Build solution
      run: |
        dotnet publish CompressMyCall.sln -c Release -r win-x86 --self-contained true /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true /p:DeleteExistingFiles=true

    - name: Upload the built executable only
      run: |
        mkdir -p ./publish
        cp **/bin/Release/net7.0-windows/win-x86/publish/CompressMyCall.exe ./publish/CompressMyCall.exe
      continue-on-error: false

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: CompressMyCall.exe
        path: ./publish/CompressMyCall.exe
  release:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: CompressMyCall.exe
          path: ./publish

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref }}
          name: Release ${{ github.ref }}
          body: |
            Automated release of CompressMyCall.exe
          draft: false
          prerelease: false
          files: ./publish/CompressMyCall.exe
